### PR TITLE
Update doc.md

### PR DESCRIPTION
**Pull request by eshapard**
Hopefully, I correctly updated the description to match the new usage in version 2.0. Congrats on a new version! I've been using ebisu as the engine for my personal review scripts for quite some time now (over a year, I think). Today, I upgraded, and instantly broke my scripts since the usage has changed. :-)

### CODE REVIEW

**Comment by fasiha** [comment]
Dohhhh 1, sorry for not updating this! I'll add this to my automatic release pipeline.

Dohh 2, sorry for breaking your app! I use semantic versioning (actually [ComVer](https://gitlab.com/staltz/comver/-/blob/master/README.md)) where I pin each dependency's version number and only auto-update minor versions, but you automatically update dependencies to the latest version even over major version numbers releases? Should I have a more graceful release process? I do want the freedom to make breaking changes but don't want to keep breaking downstream apps.

Thanks for your continued patronage and support!

**Comment by eshapard** [comment]
I forced the update through pip, so I knew it could break something. I figured if there was a new version, it couldn't be so different that I wouldn't be able to un-break it pretty easily. 

If I hadn't forced the upgrade, there would have been no problem, so I don't think anything's needed on your end.

I updated some code today to use the `exact=False` option where possible and maybe make things a tiny bit more efficient... I figured while I was at it, I might as well see if there was a new version out.

I've got some code I wrote to [handle overlapping and nested cloze deletions](https://eshapard.github.io/anki/learning/code/python/overlapping-clozes.html), which is something that was pretty awkward in Anki. I also wrote a function to identify any cloze deletions nested within the one being tested, so now they get scored along with the parent if I remember them.... cuts down on the number of cards I have to see, and addresses one of the things that was missing from Anki. (as you can see, I'm a big fan of cloze-deletions for flashcards). Just thought I'd mention that in case it interests you.

Thanks again for all your hard work on this!

**Comment by fasiha** [comment]
> I forced the update through pip, so I knew it could break something. I figured if there was a new version, it couldn't be so different that I wouldn't be able to un-break it pretty easily.

Ahh I see, ok, I was worried because this is the second time that I push out a major breaking release and you check in a day or two later 😂

> I also wrote a function to identify any cloze deletions nested within the one being tested, so now they get scored along with the parent if I remember them.... cuts down on the number of cards I have to see

Yes, absolutely, I love this! In my app, a top-level flashcard is a whole sentence, and has sub-flashcards for each vocabulary use—which you can see as a cloze-deleted card where sometimes you produce one cloze (a vocab) or all clozes (the entire sentence). Since the same vocabulary can be used in multiple sentences, reviewing one sentence updates that one flashcard's model but also all its vocabulary flashcards, which pushes the vocab-only reviews farther out.

Furthermore, each sentence or vocab card can have multiple "modalities" (I don't have a good word for it), e.g., Japanese characters↔pronunciation↔︎meaning. Reviewing one of these modalities also updates the models for all other modalities, since the one quiz exercises all those memories.

Therefore, the app builds a somewhat complicated dependency graph (or "update graph") between all the models. Once you review something, potentially several models get updated, all to reduce the time spent reviewing.

Anki/Memrise are totally unusable for me because they can't handle this basic level of complexity, but this complaint isn't so much related to the SRS algorithm they use as much as app design. So I'm happy that Ebisu is helping you deal with nested/overlapping cloze deletions, but it sounds like the primary benefit is that it's a standalone SRS algorithm that you can import into your app, and it's the app that handles the bookkeeping of creating the "update dependency graph" for you, allowing you a richer set of cards than Anki allows 😁.

**Comment by eshapard** [comment]
It sounds like we use ebisu in similar ways. Before I started working on cloze-deletion functions, I tackled Spanish verb conjugations and vocabulary.

For my Spanish studies, one of the things I do is have the computer give me a bunch of sentences using the verb tenses I'm studying. If I understand the sentence, then the tense, verb, and any vocabulary words all get scored.

I also created a bunch of other routines that decide when to introduce new cards, which vocab and phrases to learn next, etc.

Creating that kind of complex *scoring dependency tree* (or even a simple one) was something a lot of people wanted to see in Anki. I used to tell myself that as cards got easier and easier, you'd see them so infrequently that it didn't matter, but personal experience taught me otherwise.

**Pull request merged**
